### ISSUE TITLE
Modify PR's fields 

### ISSUE THREAD

**Issue by CailletOlivier** [microsoft/azure-repos-pr-multi-cherry-pick#15]
Hi,

I really appreciate this extension, because we had to do multiples cherry-picks sometimes (~10).

But, we had to modify too the title, the description and the work items linked to the PR. And we can't do this for now. 

I'll keep watching this evo about these issues. 

Thanks for this work.

**Comment by sevakraynov** [comment]
Hi,

Please, add a link to the pull request from where the cherry peak is made in the description of the new pull request, like this:

`Cherry picked from !number`

Thanks.

**Comment by erdennis13** [comment]
Thanks for using the extension! We'll investigate making these additions, but we'd also be open to taking a PR 😄

**Comment by erdennis13** [comment]
These suggestions have been implemented in #18 - we're looking forward to hearing how it works for you!
