### ISSUE TITLE
Feature request: clone linked work items

### ISSUE THREAD

**Issue by danquirk** [microsoft/azure-repos-pr-multi-cherry-pick#20]
When we cherry-pick a change across release branches we don't have a good mechanism for bug tracking. If we use the same bug for each cherry-pick PR then it is easier to track the dev work from a single bug but it also means we cannot use any of the 'auto-resolve' type features of Azure DevOps on PR completion (or if the PR uses verbiage like 'fixes #123') because otherwise if one branch PR completes and autoresolves the linked work item then it may appear safe to ship even though the other branch's PRs failed to complete. 

Is it possible to add an option on the multi cherry-pick UI to have each PR clone the work item from the existing PR and link that one instead? Adding the branch name into the bug title and/or as a metadata tag on the bug would differentiate them.

**Comment by erdennis13** [comment]
It seems like it could be implemented easily enough, but my team likely won't have time to triage it until December/January. That said, we'd absolutely take a contribution 😄

**Comment by ethanis** [comment]
@danquick - I'm finally following up on this! To me, it makes sense to copy the work item links, but not clone the work items themselves. My reasoning is that a bug isn't really "fixed" until its mitigated in all necessary branches. In this case, the "auto-resolve" type features should kick in once _all_ cherry pick PRs are completed. Feel free to chime on on #28, if you disagree 😄
