### ISSUE TITLE
No dialog appears and HTTP 404 error

### ISSUE THREAD

**Issue by cailie** [microsoft/azure-repos-pr-multi-cherry-pick#25]
Hi there,

Thank you for making this extension available. 😄 
Could you offer any advice on the following issue we are experiencing? We are eager to use this extension to streamline our workflow, so your help would be most appreciated.

**Steps to Reproduce:**

Environment: Chrome and Edge browsers, Azure DevOps Server 2019.0.1 (Version 17.143.28912.1)
1. In the Azure DevOps web portal, navigate to the pull request *Overview*.
2. Choose *Multi-cherry-pick...* from the ellipsis drop-down.

**Results:**
- The Multi-cherry-pick dialog does not appear.
- The browser console reports an HTTP 404 in response to the /_apis/git/pullRequests/<id> GET request.

**Screen Capture:**

![multi-cherry-pick-error](https://user-images.githubusercontent.com/581435/69197472-42576100-0ae6-11ea-927a-d9b87e982ffe.gif)

**Comment by erdennis13** [comment]
Hi @cailie, we've seen this happen with folks who were not using the latest Azure DevOps Server (ADOS) version (described in #16) and determined the extension only works correctly with ADOS 2019 Update 1 and forward (update docs [here](https://devblogs.microsoft.com/devops/announcing-azure-devops-server-2019-update-1-rc1/)).

Can you confirm if your ADOS instance has received the update?

**Comment by cailie** [comment]
@erdennis13 So embarrassed! I looked at the issues, but goofed up my filter so I didn't see #16. I'm sorry. I will ask for that update to be considered.

**Comment by erdennis13** [comment]
It's all good! I'll close this issue for now, but feel free to reopen if updating ADOS doesn't fix it.
